### ISSUE TITLE
黑苹果免驱网卡 蓝牙怎么驱动？

### ISSUE THREAD

**Issue by 18516329677** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#10]
老哥，我买了4930的博通网卡，无线能直接驱动，蓝牙貌似不行，hackintool 显示的蓝牙内建没有选中，是不是就没驱动？

**Comment by wjz304** [comment]
用 BrcmBluetoothInjector.kext，BrcmFirmwareData.kext，BrcmPatchRAM3.kext

**Comment by zzymissyou** [comment]
> 老哥，我买了4930的博通网卡，无线能直接驱动，蓝牙貌似不行，hackintool 显示的蓝牙内建没有选中，是不是就没驱动？

这个卡你插在这个主板的哪里？原来的卡更换么？搜索结果都是无法换网卡的。

**Comment by wjz304** [comment]
> > 老哥，我买了4930的博通网卡，无线能直接驱动，蓝牙貌似不行，hackintool 显示的蓝牙内建没有选中，是不是就没驱动？
> 
> 这个卡你插在这个主板的哪里？原来的卡更换么？搜索结果都是无法换网卡的。

可以换，但是接口限制也只额能换CNVio2的卡， 一些人是 m.2 转 miniPCIE/NGFF
