### ISSUE TITLE
请问6800xt显卡能直接用吗

### ISSUE THREAD

**Issue by zhangdp** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#12]
你好，我除了显卡是6800xt不是5700xt外其余硬件都跟大佬你一模一样，我可以直接拿来用吗？我看你加载了5700xt的acpi，这个是干嘛用的呢，去哪里找6800xt的acpi呢

**Comment by wjz304** [comment]
没记错的话，6800原生支持bigsur11.4以上版本，
5700那个是优化的，有没有影响说不好，你是是，不行就取消勾选试下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月18日(周五) 上午10:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 请问6800xt显卡能直接用吗 (#12)




 
你好，我除了显卡是6800xt不是5700xt外其余硬件都跟大佬你一模一样，我可以直接拿来用吗？我看你加载了5700xt的kexts，这个是干嘛用的呢，去哪里找6800xt的kexts呢
