### ISSUE TITLE
核显HDMI

### ISSUE THREAD

**Issue by zf1976** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#17]
核显HDMI是否无法驱动？dp正常

**Comment by wjz304** [comment]
BigSur 请勾选FakePCIID.kext 和 FakePCIID_Intel_HDMI_Audio.kext
Monterey 请不要动，勾选上述kexts 会导致频繁死机。

**Comment by zf1976** [comment]
默认是勾选了，貌似无法使用

**Comment by zf1976** [comment]
但是经过测试使用这份config_integrated.plist配置 HDMI可以使用，但DP用不了
