### ISSUE TITLE
大神，您好！我的显示器华硕的VG27AQE插上DP1.2接口后黑屏，但插HDMI2.0接口却可以亮屏，显示器自带喇叭无论如何全无声音，是否驱动问题呢？

### ISSUE THREAD

**Issue by xiaokentrl** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#23]
大神，您好！我的显示器华硕的VG27AQE插上DP1.2接口后黑屏（我没显卡，其他配置和你都一样），但插HDMI2.0接口却可以亮屏，显示器自带喇叭无论如何全无声音，是否驱动问题呢？

**Comment by wjz304** [comment]
集显啊？

**Comment by wjz304** [comment]
HDMI 是没声音，DP是可以的。核显用 config_iGPU.plist

**Comment by xiaokentrl** [comment]
> HDMI是没有声音，DP是可以的。核显用config_iGPU.plist

是核显，用什么软件修改这个config_iGPU.plist啊

**Comment by wjz304** [comment]
改名字
