### ISSUE TITLE
请问大神有没有usb3.0 u盘插上去没反应的情况

### ISSUE THREAD

**Issue by sonken87** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#26]
usb2.0的设备都可以识别，3.0的U盘无法识别，请问大神的电脑有没有这个问题

**Comment by wjz304** [comment]
19pin接口的usb吧？ 更新了试试吧

**Comment by sonken87** [comment]
大神解决了，谢谢，请问我6600xt应该用哪个plist

**Comment by wjz304** [comment]
qq 304403268

**Comment by wjz304** [comment]
https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/issues/25

**Comment by sonken87** [comment]
弄好了，这个搞好以后有什么作用吗，没有搞之前，显卡也是能驱动的

**Comment by wjz304** [comment]
如果 不卡，不弄也行

**Comment by wjz304** [comment]
19pin的3.0口吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月18日(周五) 晚上9:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 请问大神有没有usb3.0 u盘插上去没反应的情况 (Issue #26)




 
usb2.0的设备都可以识别，3.0的U盘无法识别，请问大神的电脑有没有这个问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
