### ISSUE TITLE
核显情况下播放视频，画面不动

### ISSUE THREAD

**Issue by snailhd** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#27]
无显卡，使用核显情况下，播放视频，画面不动。大佬，这个能处理吗？使用的config_iGPU.plist，cpu i9-10900

**Comment by wjz304** [comment]
没有出现你说的情况，sudo kextcache -i/ 执行这个试试吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 核显情况下播放视频，画面不动 (Issue #27)





 
无显卡，使用核显情况下，播放视频，画面不动。大佬，这个能处理吗？使用的config_iGPU.plist，cpu i9-10900
