### ISSUE TITLE
能修复一下主板拓展TypeC口吗，发现黑苹果下并不能识别硬盘

### ISSUE THREAD

**Issue by sudo-chenjiaqi** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#28]

**Comment by wjz304** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/5615843/166106521-ac06a4b0-cee6-476e-a0af-656808209642.png">
一直可以啊？

**Comment by sudo-chenjiaqi** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/90947875/166108017-80878361-40a6-445a-8a44-5dfd0404a646.png">
XHC5这个是雷电口的吧，我指的是主板上哪个拓展的C口

**Comment by wjz304** [comment]
哦，你说 sata口旁边那个 啊，额，我一直没有线，没有做定制。
你看看 接口，手动改下吧

**Comment by wjz304** [comment]
试下 USBPorts_typee.kext 吧
