### ISSUE TITLE
Sleep/Wake not working

### ISSUE THREAD

**Issue by samparhizkar** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#3]
When the computes goes to sleep, I can wake by pressing the keyboard/mouse. If I press the power button computer does a cold boot instead. So sleep basically shuts the computer off. If your configs are working can you share hackintool page please?

**Comment by wjz304** [comment]
This should have something to do with the BIOS settings, and I don't know how to set it best.

My English is not good, please forgive me.
