### ISSUE TITLE
custom bigsur

### ISSUE THREAD

**Issue by wjz304** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#34]
{"ocver": "pre", "itlwm": "big_sur", "kexts": "alpha"}

**Comment by wjz304** [comment]
说明：
1. 标题请以 custom 开头（不区分大小写），且不要包含'(单引号),"(双引号) 等转义字符。
  - eg:
  - - custom template
  - - Custom1234
  - - CUSTOM Ing 第四次
2. 内容 请以json格式编写并包含  welcome 和 custom 两项。(符号均为英文符号，内容可中文)。
  - eg:
  - - {"ocver": "pre", "itlwm": "big_sur", "kexts": "alpha"}
  - - - ocver: 'rel | pre | mod'
  - - - itlwm: 'ventura | monterey | big_sur'
  - - - kexts: 'stable | alpha'

**Comment by HzzHo** [comment]
{"ocver": "pre", "itlwm": "big_sur", "kexts": "alpha"}

**Comment by HzzHo** [comment]
custom template
{"ocver": "pre", "itlwm": "big_sur", "kexts": "alpha"}

**Comment by yuanfan-wkw** [comment]
{"ocver": "pre", "itlwm": "big_sur", "kexts": "alpha"}
