### ISSUE TITLE
关于fix drm 

### ISSUE THREAD

**Issue by zzymissyou** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#37]
配置区别 CPU i7-10700 GPU RX6600XT 选取igpu+dgpu那个config 使用时发现drm不正常，改用dgpu那个config drm依然不正常。尝试根据https://dortania.github.io/OpenCore-Post-Install/universal/drm.html 手册修复drm，不成功。
问题描述：1、运行 VDADecoderChecker反馈是正常的。2、测试[FairPlay 1.x test](https://drive.google.com/file/d/12pQ5FFpdHdGOVV6jvbqEq2wmkpMKxsOF/view)无论如何都黑屏（两个config都是如此）。3、apple music播放无损，使用蓝牙无法播放，用耳机插孔也就是内部声卡输出是可以的。4、safri播放netfilx报错。
尝试修复的手段:1、修改启动参数 删除启动参数中的shikigva=80，直接添加在DeviceProperties中，失败。2、使用OpenCore Configurator修改机型为imacpro1，1，测试[FairPlay 1.x test]闪退，其他测试失败

**Comment by wjz304** [comment]
[关于 Apple Music 中的无损音频](https://support.apple.com/zh-cn/HT212183)

**Comment by wjz304** [comment]
FairPlay 1.x 原因不详，有待调试，

**Comment by wjz304** [comment]
我几乎不看剧，netfilx一直没试过，apple TV+ 倒是可以播放，

**Comment by wjz304** [comment]
互相学习吧，
