### ISSUE TITLE
求助：请问为什么 cpu 频率一直在 5GHz

### ISSUE THREAD

**Issue by ZGW-GitHub** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#39]

**Comment by wjz304** [comment]
截图看看

**Comment by ZGW-GitHub** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44455825/183423347-d9d39a14-9207-4ae1-9c86-451109533683.png">

没有独显，EFI 用的是2天前更新的 2.1.2 ，MacOS 版本是13 public beta2

**Comment by wjz304** [comment]
10900k？

**Comment by wjz304** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/5615843/183461387-ac75e897-9228-475c-a3b7-3eb500a971f7.png">
我是正常的，明天我屏蔽独显试下

**Comment by ZGW-GitHub** [comment]
> 10900k？

10700K

**Comment by wjz304** [comment]
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/5615843/183568853-82c5653b-c0dd-41cd-ad75-b91652551ebe.png">
屏蔽独显也没有问题，进活动监视器 看下 占用的进程吧

**Comment by wjz304** [comment]
我现在是13

**Comment by ZGW-GitHub** [comment]
> 我现在是13

解决了，谢谢，13 bate 版好像有问题，有个名为 powerd 的进程占用 cpu 100 ，参考这个文章解决了：
https://zh-cn.ihowto.tips/task-manager-activity/how-to-fix-powerd-100-cpu-macos.html
