### ISSUE TITLE
Airdrop error 

### ISSUE THREAD

**Issue by samparhizkar** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#4]
I cant seem to get airdrop working. bluetooth and wifi are working though.
![Screen Shot 2020-09-27 at 11 50 01 PM](https://user-images.githubusercontent.com/6544679/94399729-c6be3b80-011c-11eb-99f5-66fcf3f1aa35.png)

**Comment by wjz304** [comment]
The author of itlwm is in development, and you can get progress here, https://github.com/OpenIntelWireless/itlwm

**Comment by wjz304** [comment]
Or use the following method, but I don't like it
http://bbs.pcbeta.com/viewthread-1870256-1-1.html
