### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by maoxikun** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#40]
请问睡眠唤醒之后过一会会自动关机是什么原因啊。

**Comment by wjz304** [comment]
软硬件环境描述一下，另外是否设置了 hibernatemode 和 proximitywake ？

**Comment by maoxikun** [comment]
> 

MSI Z490I+10850K+RX6600+macos12.5，没设置hibernatemode 和 proximitywake。
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/106460972/183589682-cc5b6d92-c5ed-4fcd-a8c6-9f81ae402020.png">

**Comment by wjz304** [comment]
设置一下 试试吧

**Comment by wjz304** [comment]
睡眠确实还是有问题

**Comment by maoxikun** [comment]
> 

正常睡正常醒，不确定是不是睡眠导致的关机，我先设置下试试。

**Comment by wjz304** [comment]
可以在控制台里找下关机事件

**Comment by maoxikun** [comment]
> 

刚把日志清了，等复现再看看。

**Comment by maoxikun** [comment]
> 可以在控制台里找下关机事件

又出现这个问题了，关机事件咋看啊，只看到系统日志
Aug 11 18:31:08 iMac syslogd[132]: ASL Sender Statistics
Aug 11 18:32:56 localhost bootlog[0]: BOOT_TIME 1660213976 0
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.cdscheduler" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.install" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/asl" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.authd" sharing output destination "/var/log/system.log" with ASL Module "com.apple.asl".
	Output parameters from ASL Module "com.apple.asl" override any specified in ASL Module "com.apple.authd".
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.authd" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.eventmonitor" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.mail" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.performance" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.iokit.power" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.contacts.ContactsAutocomplete" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.mkb" sharing output destination "/private/var/log/keybagd.log" with ASL Module "com.apple.mkb.internal".
	Output parameters from ASL Module "com.apple.mkb.internal" override any specified in ASL Module "com.apple.mkb".
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.mkb" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost syslogd[132]: Configuration Notice:
	ASL Module "com.apple.MessageTracer" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 11 18:32:57 localhost Installer Progress[129]: Progress UI App Starting
Aug 11 18:32:57 localhost syslogd[132]: ASL Sender Statistics

**Comment by wjz304** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/5615843/184287473-16f5fff1-86c1-42dc-9f95-b1758c5eb341.png">
看看这里

**Comment by wjz304** [comment]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/5615843/184287562-1b467e99-72f5-4734-93af-936e27992bf7.png">
和这里

**Comment by wjz304** [comment]
再看看 崩溃报告里有没有那个时间点的崩溃信息

**Comment by maoxikun** [comment]
> 再看看 崩溃报告里有没有那个时间点的崩溃信息

没崩溃信息

**Comment by wjz304** [comment]
你取下 关机的那段时间的日志 看看

**Comment by maoxikun** [comment]
> 

没看到那时间的日志，目前开启了booter下两个quirks：DevirtualiseMmio和ProtectUefiServices，暂时没有出现睡眠唤醒关机的情况了。

**Comment by wjz304** [comment]
https://oc.skk.moe/12-troubleshooting.html#:~:text=9.%20%E6%88%91%E5%BA%94%E8%AF%A5,Quirk%20%E7%9A%84%E6%8F%8F%E8%BF%B0%E3%80%82

**Comment by wjz304** [comment]
测试了一下，虽然我不改没有出现类似的问题，但是改了应该会好点，已投到线上。

**Comment by lunasaw** [comment]
![image](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/52351139/2f738726-6527-4f70-ab40-2a56409b111a)
我也遇到了同样的问题 ，并且我尝试将休眠模式改为传统模式
![image](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/52351139/9983dc7b-ccd9-44de-89bd-dfd97d64bc40)
并没有得到解决，日志
![image](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/52351139/4ed18e33-e635-40d5-b5f8-41c1d285157b)

**Comment by maoxikun** [comment]
> 睡眠唤醒之后过一会会自动关机是什么原因

把cpu和内存超频啥的关了试试

**Comment by maoxikun** [comment]
> ![image](https://user-images.githubusercontent.com/52351139/255387988-2f738726-6527-4f70-ab40-2a56409b111a.png) 我也遇到了同样的问题 ，并且我尝试将休眠模式改为传统模式 ![image](https://user-images.githubusercontent.com/52351139/255388133-9983dc7b-ccd9-44de-89bd-dfd97d64bc40.png) 并没有得到解决，日志 ![image](https://user-images.githubusercontent.com/52351139/255388213-4ed18e33-e635-40d5-b5f8-41c1d285157b.png)

把cpu和内存超频啥的关了试试
