### ISSUE TITLE
雷电口一些疑问

### ISSUE THREAD

**Issue by maoxikun** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#45]
1、好像雷电口接usb2.0设备只能充电不能传输数据，连接ipad或者手机只能充电
2、开机有TBDU错误，看名字好像是雷电设备的问题
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/106460972/208818279-69d36840-7666-4df8-a45c-d6a94ab812a7.png">

**Comment by wjz304** [comment]
1、好像雷电口接usb2.0设备只能充电不能传输数据，连接ipad或者手机只能充电
>是的, 由于15个usb口的限制，typec 口的2.0 一直没有定制, 只定制了3.0.  
我都写了注释，你可以通过 `<dict><string>` 知道现在定制的接口[USBPorts.kext](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/blob/master/EFI/OC/Kexts/USBPorts_9pin.kext/Contents/Info.plist)  

2、开机有TBDU错误，看名字好像是雷电设备的问题
>这个问题从一开始就一直存在，能力有限，开始尝试过解决，后来比较忙也就没在解决了，你有任何见解 都可以PR。

**Comment by maoxikun** [comment]
了解，还以为雷电口出问题了

**Comment by maoxikun** [comment]
> 1、好像雷电口接usb2.0设备只能充电不能传输数据，连接ipad或者手机只能充电
> 
> > 是的, 由于15个usb口的限制，typec 口的2.0 一直没有定制, 只定制了3.0.
> > 我都写了注释，你可以通过 `<dict><string>` 知道现在定制的接口[USBPorts.kext](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/blob/master/EFI/OC/Kexts/USBPorts_9pin.kext/Contents/Info.plist)
> 
> 2、开机有TBDU错误，看名字好像是雷电设备的问题
> 
> > 这个问题从一开始就一直存在，能力有限，开始尝试过解决，后来比较忙也就没在解决了，你有任何见解 都可以PR。



> 1、好像雷电口接usb2.0设备只能充电不能传输数据，连接ipad或者手机只能充电
> 
> > 是的, 由于15个usb口的限制，typec 口的2.0 一直没有定制, 只定制了3.0.
> > 我都写了注释，你可以通过 `<dict><string>` 知道现在定制的接口[USBPorts.kext](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/blob/master/EFI/OC/Kexts/USBPorts_9pin.kext/Contents/Info.plist)
> 
> 2、开机有TBDU错误，看名字好像是雷电设备的问题
> 
> > 这个问题从一开始就一直存在，能力有限，开始尝试过解决，后来比较忙也就没在解决了，你有任何见解 都可以PR。

好像单个控制器没超过15个就行，机箱后置全部接口+前置面板（主板内部usb3+typec，我机箱是乔思伯d40，前面板没独立usb2接口）刚好15个，雷电口的usb2是和前面板一个控制器，雷电口的usb3是另一个控制器，目前所有定制过的接口正常使用，有线随航的时候lighting线终于不用绕机箱一圈了

**Comment by wjz304** [comment]
是的，2个控制器 一共可以 16个，

z490i unify 一共就这20个.
https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/blob/master/screenshot/USB_Map.txt

USBPorts_9pin.kext 舍弃了 红口的2.0，type-e的2.0&3.0，和typec的2.0
USBPorts_typee.kext 舍弃了 红口的2.0，9pin的2个2.0，和typec的2.0

**Comment by wjz304** [comment]
特殊情况 参考这个文件自己改下就好了。我也只能照顾大多数人的需求。
