### ISSUE TITLE
OC主题背景无法全屏问题

### ISSUE THREAD

**Issue by GodDamnGitHub** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#46]
作者大大你好，我是黑果小白，所以这可能是个很简单的问题，希望不要见怪。
我想要更换启动时的主题背景，但是无论是直接替换background.icns，还是把resources文件夹整个替换，都无法让背景图片全屏显示（4k显示器）。我确定我找的主题都是4k分辨率，这可能是什么原因呢？

**Comment by wjz304** [comment]
用我的是全屏吧？
如果是，那就是 background.icns 的问题。

**Comment by wjz304** [comment]
https://github.com/chris1111/Icnspack-Builder
