### ISSUE TITLE
Blueetooh problem.

### ISSUE THREAD

**Issue by duskyzao** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#48]
Hi, how are you ?

Thanks for the great job!

I am using the last pre-release version, my WIFI its ok, My bluetooth is ON, bluetooth can see other devices but can't connect in anything.

How can I change LPM version in IntelBTPatcher.kext?

I am using the last version of Ventura, 13.1

Best regards

**Comment by wjz304** [comment]
确定lpm的版本，尝试取消IntelBTPatcher.kext

**Comment by wjz304** [comment]
https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer
