### ISSUE TITLE
itlwm开启就崩溃

### ISSUE THREAD

**Issue by way1001** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#5]
你好，大佬，板U其他外设硬件几乎一样，config.plist没有开启itlwm，我尝试开启引导就直接崩溃，请问还需要配置哪里？

**Comment by wjz304** [comment]
之前是用的itlwm，后来作者更新了airportitwm,，就用airportitwm了， airportitwm 不需要 Heliport。
你为什么开启itlwm，WIFI不好使吗？

**Comment by way1001** [comment]
谢谢大佬回复，每次电脑关机后，下次再开机，wifi是好的，不过要等1分钟左右的样子才能连接上，但是蓝牙不可用，然后再重启，蓝牙就恢复了，找不到原因，就瞎尝试在。

**Comment by wjz304** [comment]
是的，是有这个问题，蓝牙和 usb有一些关系，最近没时间搞，wifi 等 airportitwm 更新看看吧
