### ISSUE TITLE
DP音频偶尔消失

### ISSUE THREAD

**Issue by maoxikun** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#50]
显示器接的独显DP口，睡眠唤醒之后DP音频输出偶尔会消失，开关显示器之后会恢复
<img width="598" alt="1" src="https://user-images.githubusercontent.com/106460972/220496097-92220c25-27a2-4ada-bdf8-d25da0f71a65.png">

**Comment by wjz304** [comment]
什么卡

**Comment by maoxikun** [comment]
> 什么卡

华硕rx6600

**Comment by wjz304** [comment]
尝试切换dp口，尽量插第一个，如无果 尝试 启动参数添加 igfxonln=1

**Comment by maoxikun** [comment]
> 尝试切换dp口，尽量插第一个，如无果 尝试 启动参数添加 igfxonln=1

igfxonln=1这个参数对独显也生效吗，最近没复现出来

**Comment by wjz304** [comment]
都是 WhateverGreen.kext 的参数,

**Comment by maoxikun** [comment]
> 都是 WhateverGreen.kext 的参数,

试了还是不管用，不折腾了，反正用不上
