### ISSUE TITLE
升级到Ventura自动唤醒

### ISSUE THREAD

**Issue by maoxikun** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#53]
Monterey正常睡眠唤醒，升级到Ventura之后，每次睡眠唤醒之后系统报告里面都会多出两个电源事件，导致睡眠之后自动唤醒
<img width="903" alt="image" src="https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/106460972/bed15bf1-6dbe-47c6-ad55-c3d0b636c417">

**Comment by wjz304** [comment]
最近有点忙，不想搞，等 intel 网卡驱动搞定了在一起看看吧

**Comment by maoxikun** [comment]
> 

搜了下好像白苹果也有，应该是系统问题
