### ISSUE TITLE
技嘉z490i小雕+10600k睡眠和重启的问题

### ISSUE THREAD

**Issue by lunasaw** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#57]
我的技嘉z490i小雕+10600k用这个EFI使用正常，非常感谢🙏。有一个问题是睡眠会重启，根据hackintool电源修复后，会出现无法深度睡眠，风扇不停，但是能正常唤醒，并且重启也是无法断电，需要长按关机键断电，关机操作可以正常断电。因为网卡和蓝牙使用BCM4360我仅启动和禁用了一些驱动，其他并无修改
<img width="1259" alt="image" src="https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/52351139/196629f4-2358-4077-a027-fea247718b4a"> 有修复建议的话还请大佬们指点指点

**Comment by wjz304** [comment]
https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/issues/40
看下这里的几个链接是否有帮助，最近比较忙
