### ISSUE TITLE
z490i unify卡在SMCSuperIO

### ISSUE THREAD

**Issue by SolarTorch** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#58]
![IMG_3374](https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/10752372/532d2575-33b6-4d62-8ae9-d27d06fce1b9)

主板是MSI Trident X 10th带的Z490i。和零售版可能有些许区别，总之会卡在ACPI这里。

**Comment by wjz304** [comment]
取消wifi的kext试试吧，近段时间电脑不在身边





------------------ 原始邮件 ------------------
发件人: Helang Liu ***@***.***&gt;
发送时间: 2023年7月26日 04:28
收件人: wjz304/Hackintosh-EFI-MSI-Z490i-Unify ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 应该是不同版本的Z490i出现的问题 (Issue #58)





 

 
主板是MSI Trident X 10th带的Z490i。和零售版可能有些许区别，总之会卡在ACPI这里。

**Comment by SolarTorch** [comment]
> 取消wifi的kext试试吧，近段时间电脑不在身边
> […](#)

感谢回复，我去试一下。
