### ISSUE TITLE
蓝牙无LEA服务

### ISSUE THREAD

**Issue by maoxikun** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#59]
蓝牙LEA服务好像不生效
<img width="903" alt="image" src="https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/106460972/a11e9059-72cd-4806-906e-2679fe09495e">

**Comment by wjz304** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by wjz304** [comment]
最近太忙了

**Comment by maoxikun** [comment]
> 最近太忙了

好吧，还以为你也是用半载网卡呢
