### ISSUE TITLE
无法升级系统

### ISSUE THREAD

**Issue by ZGW-GitHub** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#62]
<img width="498" alt="image" src="https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify/assets/44455825/a324e1eb-635e-45f4-bce3-60310977bceb">

用的最新的 release（非脚本自动发布的 release），config 用的是核显那个

**Comment by wjz304** [comment]
Dev 6 Pub 4  (23A5328b)--2023-08-23  
https://swcdn.apple.com/content/downloads/44/25/042-37835-A_BEAOB8L7HU/1qzvpcz2hplmg557cci42sr49egqus76v1/InstallAssistant.pkg


Dev 5 Pub 3  (23A5312d)--2023-08-08  
https://swcdn.apple.com/content/downloads/26/36/042-27162-A_4GKRLRWELJ/qyzyo86g692wlsewkyclfk686op47kuq5c/InstallAssistant.pkg

Dev 4 Pub 2 (23A5301h)--2023-07-31  
https://swcdn.apple.com/content/downloads/41/53/042-25574-A_YJ7607N1CB/dwkoslehspd77g1c717yvjfdpj9rq6c1s4/InstallAssistant.pkg

**Comment by ZGW-GitHub** [comment]
> Dev 6 Pub 4 (23A5328b)--2023-08-23 https://swcdn.apple.com/content/downloads/44/25/042-37835-A_BEAOB8L7HU/1qzvpcz2hplmg557cci42sr49egqus76v1/InstallAssistant.pkg
> 
> Dev 5 Pub 3 (23A5312d)--2023-08-08 https://swcdn.apple.com/content/downloads/26/36/042-27162-A_4GKRLRWELJ/qyzyo86g692wlsewkyclfk686op47kuq5c/InstallAssistant.pkg
> 
> Dev 4 Pub 2 (23A5301h)--2023-07-31 https://swcdn.apple.com/content/downloads/41/53/042-25574-A_YJ7607N1CB/dwkoslehspd77g1c717yvjfdpj9rq6c1s4/InstallAssistant.pkg

好的，谢谢
