### ISSUE TITLE
Sonoma 14(b) 没有WiFi , WiFi驱动失败

### ISSUE THREAD

**Issue by xiaokentrl** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#65]
Sonoma 14(b) WiFi驱动失败

补充：
默认可以驱动了，是我太急了，我重启系统后发现能打开了。

不好意思，兄弟

**Comment by wjz304** [comment]
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha

**Comment by wjz304** [comment]
14.4 前后的驱动不互相兼容，暂时我也不想在下层处理

**Comment by wjz304** [comment]
你自己替换一下吧

**Comment by xiaokentrl** [comment]
> 默认可以驱动了，是我太急了，我重启系统后发现能打开了。
> 
> 不好意思，兄弟


默认可以驱动了，是我太急了，我重启系统后发现能打开了。

不好意思，兄弟
