### ISSUE TITLE
Sequoia 15 蓝牙不能使用

### ISSUE THREAD

**Issue by Lasx** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#69]
Sequoia 15 蓝牙不能使用。其它正常

**Comment by Malumen** [comment]
> Sequoia 15 蓝牙不能使用。其它正常

There is a new BETA version of BlueTooth, I believe it is 2.5.0; it has support for BE200 devices and Sequoia basic support. 

You must hunt for the file in here: [https://github.com/OpenIntelWireless/IntelBluetoothFirmware/actions](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/actions)

**Comment by lion9966** [comment]
蓝牙，通过升级蓝牙文件到2.5.0（IntelBluetoothInjector.kext和IntelBluetoothFirmware.kext和IntelBTPatcher.kext），并在NVRAM内7C436110-AB2A-4BBB-A880-FE41995C9F82内加入2项值（bluetoothExternalDongleFailed和bluetoothInternalControllerInfo）蓝牙问题可以解决，但是Wi-Fi（itlwm.kext现在还是没办法解决，曲线使用HeliPort凑合，但是不完美）

**Comment by wjz304** [comment]
v2.4.0
