### ISSUE TITLE
Sequoia 15 Wi-Fi打不开

### ISSUE THREAD

**Issue by lion9966** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#70]
升级后14也打不开，WiFi, 升级系统后成15.1也是一样，无法打开
![截屏2024-11-12 20 35 59](https://github.com/user-attachments/assets/6280d1a8-1e43-47d0-8de6-f4d1a6042466)
![截屏2024-11-12 20 41 35](https://github.com/user-attachments/assets/c47d4bb0-679c-420f-a73b-d58eecdc9d60)

**Comment by wjz304** [comment]
使用HeliPort
