### ISSUE TITLE
升级macos sequoia无线上网无法使用

### ISSUE THREAD

**Issue by zem12345678** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#71]
无线上网无法使用
<img width="1585" alt="截屏2024-12-16 04 55 32" src="https://github.com/user-attachments/assets/90e2a254-07d2-45ed-bc7c-1e4eb3095dc8" />
<img width="474" alt="截屏2024-12-16 04 58 55" src="https://github.com/user-attachments/assets/e2c040d1-ee7f-4fae-b6c1-b7ce9d737159" />

**Comment by JackHuang021** [comment]
哈哈，我也搞到今天凌晨两三点才升级到mscos15，intel无线网卡有解决方法可以用起来，好像z490i unify换无线网卡的话还不太好换，我基本也没用过无线，就没管这个问题了，我的硬件是11代u，rx6600的显卡

**Comment by wjz304** [comment]
![image](https://github.com/user-attachments/assets/bd747fab-b445-4377-962d-b954472d59c5)
