### ISSUE TITLE
AppleALC

### ISSUE THREAD

**Issue by wangSq1014** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#8]
主板上的耳机输出没有声音，前面板有声音，可能是哪里出了问题？
<img width="1266" alt="截屏2021-01-08 上午1 02 31" src="https://user-images.githubusercontent.com/25403315/103921253-3cd73300-514d-11eb-810d-7f712db5dd9f.png">

**Comment by wangSq1014** [comment]
新发现，前置不插耳机的时候开机，后置就正常了，但这时候再插前置没反应

**Comment by wjz304** [comment]
很抱歉，我最近没有什么时间，另外由于我没有音响设备也没有接入前置面板，所以并没有深度测试，有时间我试一下。
