### ISSUE TITLE
What the version of opencore?

### ISSUE THREAD

**Issue by milkpeanut** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#9]

**Comment by milkpeanut** [comment]
My hardwork almost the same wiht you except I don't have a dGpu.My audio doesn't work well by using your efi.

**Comment by wjz304** [comment]
Try switching the sound output device.

**Comment by wjz304** [comment]
系统偏好设置-声音-输出

**Comment by milkpeanut** [comment]
0 0，试过切换过了，还是没声音。一共有三个，切换全都没声音

**Comment by wjz304** [comment]
你配置那个efi 是有声音的吗？其实我没有试过 音频，因为我没有线，我是hdmi输出。看来我得找个线试试。

**Comment by wjz304** [comment]
qq: 304403268

**Comment by milkpeanut** [comment]
我的efi是有声音的，就是版本是0.6.0，想用wifi只好升级。刚好就找到你的了

**Comment by milkpeanut** [comment]
已经在qq上加你了。
